#!/bin/bash

if [ "x$1" = "xrbenv" ]; then
  if [ -d "${HOME}/.rbenv" ]; then
    export PATH="${HOME}/.rbenv/bin:${PATH}"
    eval "$(rbenv init -)"
  fi
fi

ln -s 'tests/db' .

bundle install
rake

