# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hoplang"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrey Adinetz", "Sergey Zhumatiy"]
  s.date = "2012-09-19"
  s.description = "Hoplang is innovative parallel cool data strams processing language"
  s.email = "serg@parallel.ru, adinetz@gmail.com"
  s.extra_rdoc_files = [
    "README",
    "README.md"
  ]

  s.files = `git ls-files`.split("\n")
  s.test_files = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ['lib']

  s.homepage = "http://github.com/zhum/hoplang"
  s.rubygems_version = "1.8.23"
  s.summary = "Innovative parallel cool data strams processing language"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
#      s.add_runtime_dependency(%q<yard>, [">= 0"])
#      s.add_runtime_dependency(%q<rspec>, [">= 0"])
#      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<mongo>, [">= 0"])
      s.add_runtime_dependency(%q<bson_ext>, [">= 0"])
      s.add_runtime_dependency(%q<citrus>, [">= 0"])
      s.add_runtime_dependency(%q<home_run>, [">= 0"])
    else
#      s.add_dependency(%q<yard>, [">= 0"])
#      s.add_dependency(%q<rspec>, [">= 0"])
#      s.add_dependency(%q<jeweler>, [">= 0"])
#      s.add_dependency(%q<mongo>, [">= 0"])
      s.add_dependency(%q<bson_ext>, [">= 0"])
      s.add_dependency(%q<citrus>, [">= 0"])
      s.add_dependency(%q<home_run>, [">= 0"])
    end
  else
#    s.add_dependency(%q<yard>, [">= 0"])
#    s.add_dependency(%q<rspec>, [">= 0"])
#    s.add_dependency(%q<jeweler>, [">= 0"])
#    s.add_dependency(%q<mongo>, [">= 0"])
    s.add_dependency(%q<bson_ext>, [">= 0"])
    s.add_dependency(%q<citrus>, [">= 0"])
    s.add_dependency(%q<home_run>, [">= 0"])
  end
end

