#!/usr/bin/ruby
# coding: UTF-8
require 'thread'

Encoding.default_internal = Encoding.default_external = Encoding::UTF_8

Thread.abort_on_exception = true

begin

  require './hoplang.rb'
  include Hopsa

  file_found = nil
  ARGV.each do |a|
    # miss arguments
    next if a =~  /([^=]+)=(.+)/
    file_found = true
    text=[]
    File.open(a).each do |line|
      text.push line
    end
    ex=load_program(text)
    ex.hop
  end
  unless file_found
    while $stdin.fgets
      text.push $_
    end
    ex=load_program(text)
    ex.hop
  end
rescue => e
  puts "--"
  puts "Error: #{e.message}"
  puts 'Trace: '+(e.backtrace.map {|m| m.force_encoding('utf-8')}).join("\t\n");
  exit 100
end
