require 'echoe'

Echoe.new("hopcsv") do |p|
  p.author = "Sergey Zhumatiy, Evan Weaver"
#  p.project = "HOPSA"
  p.summary = "A pure-C CSV parser for HOPSA. Based on Ccsv project."
  p.url = "http://github.com/zhum/hopcsv"
  p.docs_host = "http://github.com/zhum/"
end
